apiVersion: v1
kind: Pod
metadata:
  name: service-b
spec:
  containers:
  - name: service-b
    image: service-b
    env:
    - name: JAEGER_SERVICE_NAME
      value: "service-b"
    - name: JAEGER_AGENT_HOST
      value: "jaeger"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
    - name: JAEGER_REPORTER_LOG_SPANS
      value: "true"
